---
python_version: 3.8.13
python_dependencies:
  - build-essential
  - zlib1g-dev
  - libncurses5-dev
  - libgdbm-dev
  - libnss3-dev
  - libssl-dev
  - libsqlite3-dev
  - libreadline-dev
  - libffi-dev
  - curl
  - libbz2-dev