---
- name: Download kind binary
  shell: "[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64"

- name: Give execution permission
  file:
    path: ./kind
    state: file
    mode: +x

- name: Move binary to bin/
  shell: mv ./kind /usr/local/bin/kind
  become: yes
  