---
- name: Install environment
  hosts: all
  roles:
    #  - apt_packages
    #  - nvim
    #  - fish
    - tmux  
    #  - vim
    #  - git
    #  - github
    #  - docker
    #  - kubernetes
    #  - kind
