---
- name: Install environment
  hosts: all
  roles:
  - nvim
    #    - apt_packages
    #    - fish
    #    - vim
    #    - git
    #    - github
    #    - docker
    #    - kubernetes
    #    - kind
