---
- name: Install environment
  hosts: all

  vars:
    home_dir: /home/mmazoni
    user: mmazoni

  tasks:
  - name: Update system packages
    apt:
      update_cache: yes
      upgrade: safe
    become: yes
  
  - name: Install packages
    apt: 
      name: "{{ item }}"
      state: latest
    with_items:
      - fish
      - git
      - vim
    become: yes

  - name: Create fish config directory
    file: 
      path: "{{ home_dir }}/.config/fish"
      state: directory
      mode: 0755

  - name: Download the fish config file
    get_url:
      url: https://raw.githubusercontent.com/MMazoni/configuration-files/master/.config/fish/config.fish
      dest: "{{ home_dir }}/.config/fish/config.fish"

  - name: Add fish to shell
    shell: chsh -s $(which fish) "{{ user }}"
    become: yes

  - name: Execute fish to install the theme
    shell: fish

  - name: Download vim confiruration file
    get_url:
      url: https://raw.githubusercontent.com/MMazoni/configuration-files/master/.vimrc
      dest: "{{ home_dir }}/.vimrc"
    
  - name: Create vim themes directory
    file: 
      path: "{{ home_dir }}/.vim/colors"
      state: directory
      mode: 0755

  - name: Download atlantic-dark vim theme file
    get_url:
      url: https://raw.githubusercontent.com/MMazoni/configuration-files/master/.vim/colors/atlantic-dark.vim
      dest: "{{ home_dir }}/.vim/colors/atlantic-dark.vim"

  - name: Execute vim to install the libs and theme
    shell: vim
    