---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: safe
  become: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - fish
    - git
    - vim
    - curl
    - wget
    - gh
    - zip
  become: yes
