---
- name: Install dependencies to Docker
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  become: yes
  
- name: Get docker to source list
  shell: "{{ item }}"
  loop:
    - "curl -fsSL https://download.docker.com/linux/{{ distro }}/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ distro }} $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install docker
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes
  
  
- name: Create docker group
  group:
    name: docker
    state: present
  become: yes
  
- name: Add ansible_env.USER to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes
